site_name: Video Conferencing with Zoom API Plugin Documentation
nav:
  - Getting Started: index.md
  - Zoom Pro Plans: zoom_plans.md
  - API Keys Integration: integration.md
  - Shortcode Implementation: shortcode.md
  - Vanity URL: vanity_url.md
  - Template Override: template_override.md
  - Meeting Types: meeting_types.md
  - Join Links: join_links.md
  - Filter Hooks: filters_hooks.md
  - Assign Host Page: assign_host.md
  - WooCommerce (Addon): woocommerce.md
  - WooCommerce Bookings (Addon): woocommerce-booking.md
theme: readthedocs